# This is a basic workflow to help you get started with Actions

name: packer

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
    #branches: [ main ]
    
  #schedule:
    # * is a special character in YAML so you have to quote this string
    #- cron:  '30 1 * * *'
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  init:
    runs-on: self-hosted
    steps:
      - name: pull latest repo
        working-directory: /home/nutanix/packer/centos7
        run: git pull --recurse-submodules
      - name: Checkout submodules
        working-directory: /home/nutanix/packer/centos7
        run: git submodule update --init --recursive /home/nutanix/packer/centos7
      - name: packer init centos79.pkr.hcl
        working-directory: /home/nutanix/packer/centos7
        run: packer init centos79.pkr.hcl

      
  validate:
    runs-on: self-hosted
    needs: init
    steps:
      - name: packer validate centos79.pkr.hcl
        working-directory: /home/nutanix/packer/centos7
        run: packer validate centos79.pkr.hcl
