# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
    #branches: [ main ]
    
  #schedule:
    # * is a special character in YAML so you have to quote this string
    #- cron:  '30 1 * * *'
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  init:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: packer init centos79.pkr.hcl
        run: packer init centos79.pkr.hcl
      - name: packer init centos79-lvm.pkr.hcl
        run: packer init centos79-lvm.pkr.hcl
      
  validate:
    runs-on: self-hosted
    needs: init
    steps:
      - uses: actions/checkout@v2
      - name: packer validate centos79.pkr.hcl
        run: packer validate centos79.pkr.hcl
      - name: packer validate centos79-lvm.pkr.hcl
        run: packer validate centos79-lvm.pkr.hcl
